development:
  adapter: postgresql
  database: resume_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: resume_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: resume_production
  pool: 5
  timeout: 5000
